version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - my-app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - my-app-network
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8123:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-app-network
    depends_on:
      - frontend
      - backend

networks:
  my-app-network:
    driver: bridge