version: '3.8'

services:
  doc2md:
    build: .
    ports:
      - "5174:5174"  # 前端端口
      - "3000:3000"  # 后端端口
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped 